# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NatCubic_SplineGrowth_loglike_cubicspline <- function(params, param_i, data, misc) {
    .Call(`_COVIDCurve_NatCubic_SplineGrowth_loglike_cubicspline`, params, param_i, data, misc)
}

