# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

natcubspline_loglike_binomial <- function(params, param_i, data, misc) {
    .Call(`_COVIDCurve_natcubspline_loglike_binomial`, params, param_i, data, misc)
}

natcubspline_loglike_logit <- function(params, param_i, data, misc) {
    .Call(`_COVIDCurve_natcubspline_loglike_logit`, params, param_i, data, misc)
}

