# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SplineGrowth_loglike <- function(params, param_i, data, misc) {
    .Call(`_COVIDCurve_SplineGrowth_loglike`, params, param_i, data, misc)
}

